In [1]:
#Import dependencies
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import NearestNeighbors as NN
import pydotplus
from IPython.display import Image
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
#read CSV file into a pandas DataFrame
coffee_data = pd.read_csv("final data set/coffee_clean_final.csv", index_col=0)
coffee_data.head()

FileNotFoundError: [Errno 2] File final data set/coffee_clean_final.csv does not exist: 'final data set/coffee_clean_final.csv'

In [ ]:
print(coffee_data.columns)

Index(['title', 'rating', 'acidity_structure', 'aftertaste', 'aroma', 'body',
       'flavor', 'blind_assessment', 'coffee_origin', 'notes', 'roast_level',
       'city', 'state', 'usd_per_oz'],
      dtype='object')


In [ ]:
# Encode the categorical variables
label_encoder = LabelEncoder()
coffee_data['roast_level'] = label_encoder.fit_transform(coffee_data['roast_level'])
#coffee_data['coffee_origin'] = label_encoder.fit_transform(coffee_data['coffee_origin'])

In [ ]:
coffee_data.head()

title  rating  acidity_structure  \
0                      Bolivia Manantial Gesha    93.0                9.0   
1  Yellow Pacamara Carbonic Maceration Nanolot    92.0                8.0   
2                   Ethiopia Gera Genji Challa    94.0                9.0   
3                 Yirgacheffe Mengesha Natural    94.0                9.0   
4           Tropical Summer Colombia La Sierra    93.0                9.0   

   aftertaste  aroma  body  flavor  \
0         8.0    9.0   8.0     9.0   
1         8.0    9.0   8.0     9.0   
2         8.0    9.0   9.0     9.0   
3         8.0    9.0   9.0     9.0   
4         8.0    9.0   8.0     9.0   

                                    blind_assessment  \
0  Richly aromatic, floral-toned. Magnolia, cocoa...   
1  Crisply sweet-savory. White peach, hop flowers...   
2  Delicately aromatic, complex. Lilac, cocoa nib...   
3  High-toned, fruit-driven. Boysenberry, pear, c...   
4  Fruit-driven, crisply chocolaty. Goji berry, d...   

                                    coffee_origin  \
0                               Caranavi, Bolivia   
1             Matagalpa growing region, Nicaragua   
2  Agaro Gera, Jimma Zone, Oromia State, Ethiopia   
3   Yirgacheffe growing region, southern Ethiopia   
4           La Sierra, Cauca Department, Colombia   

                                               notes  roast_level  \
0  Produced by Angel Mamani Chambi, entirely of t...            4   
1  Produced by Benjamin Weiner at Finca Idealista...            4   
2  Ethiopia coffees like this one are largely pro...            4   
3  Produced at Mengesha Farm from selections of i...            4   
4  Produced by smallholding farmers from trees of...            4   

           city        state  usd_per_oz  
0         Floyd     Virginia        2.50  
1     Cleveland         Ohio       13.33  
2     San Diego   California        2.33  
3      Glendale   California        1.71  
4  Harrisonburg     Virginia        2.37

In [ ]:
print(coffee_data['roast_level'].unique())
print(coffee_data['acidity_structure'].unique())
print(coffee_data['aroma'].unique())
print(coffee_data['flavor'].unique())

[4 1 2 3 0]
[ 9.  8.  7.  6. 10.  1.  3.]
[ 9. 10.  8.  7.  2.  3.]
[ 9.  8. 10.  7.  2.  3.]


In [ ]:
# Specify the features we want to use for recommendations
features = ['roast_level', 'acidity_structure', 'aroma', 'flavor']

In [ ]:
features

['roast_level', 'acidity_structure', 'aroma', 'flavor']

In [ ]:
# Fit the nearest neighbors model on the coffee dataset
model = NN(n_neighbors=5, algorithm='ball_tree')
model.fit(coffee_data[features])

NearestNeighbors(algorithm='ball_tree')

In [ ]:
coffee_data.dtypes

title                 object
rating               float64
acidity_structure    float64
aftertaste           float64
aroma                float64
body                 float64
flavor               float64
blind_assessment      object
coffee_origin         object
notes                 object
roast_level            int32
city                  object
state                 object
usd_per_oz           float64
dtype: object

In [ ]:
# Ask the user for their preferences
roast = int(input("What roast level do you like(on a scale of 0-5)? "))
acidity = float(input("How acidic do you like your coffee (on a scale of 0-10)? "))
aroma = float(input("How aromatic do you like your coffee (on a scale of 0-10)? "))
flavor = float(input("How flavorful do you like your coffee (on a scale of 0-10)? "))
#price = float(input("What is your budget per 12 ounces of coffee? "))

In [ ]:
# Make a prediction based on the user's preferences
query = [[roast, acidity, aroma, flavor]]
distances, indices = model.kneighbors(query)

c:\Users\ankit\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but NearestNeighbors was fitted with feature names
  warnings.warn(


In [ ]:
# Print out the top 5 recommendations for the user
print("Top 5 recommendations based on your preferences:")
for i in indices[0]:
    print(coffee_data.iloc[i]['title'])
    print(coffee_data.iloc[i]['rating'])
    print(coffee_data.iloc[i]['blind_assessment'])

Top 5 recommendations based on your preferences:
CBD Coffee Dark Roast
84.0
Chocolaty, smoke-toned, sweetly savory. Dark chocolate, scorched mesquite, vanillin, gardenia, prune in aroma and cup. Sweet-savory structure with very little acidity; light-bodied, smooth mouthfeel. Wood-framed finish with hints of smoky chocolate.
Skyway Fair Trade Organic Blend
86.0
Prominently roast-toned. Prune, gardenia, raw cacao, tobacco, scorched mesquite in aroma and cup. Bittersweet structure with imperceptible acidity; creamy, dry mouthfeel. Tobacco and prune notes carry the finish.
Premium Coffee (Instant Coffee)
68.0
Evaluated at proportions of 5 grams of instant coffee powder mixed with 8.5 ounces (250 ml) of hot water. Not attractive. Rotten suggestions (composted orange, lily) and acrid wood dominate, along with a metallic note. On the positive side, hints of prune, salty caramel, cardamom. Bittersweet and acrid in structure; lean but smooth in mouthfeel. Continued bitter and acrid in the finis

In [ ]:
# Define features set
X = coffee_data.copy()
X.drop(["title", "body", "blind_assessment", "aftertaste", "coffee_origin", "notes", "rating"], axis=1, inplace=True)
X.head()

acidity_structure  aroma  flavor  roast_level          city        state  \
0                9.0    9.0     9.0            4         Floyd     Virginia   
1                8.0    9.0     9.0            4     Cleveland         Ohio   
2                9.0    9.0     9.0            4     San Diego   California   
3                9.0    9.0     9.0            4      Glendale   California   
4                9.0    9.0     9.0            4  Harrisonburg     Virginia   

   usd_per_oz  
0        2.50  
1       13.33  
2        2.33  
3        1.71  
4        2.37

In [ ]:
# Define target vector
y = coffee_data["title"].values.reshape(-1, 1)
y[:5]

array([['Bolivia Manantial Gesha'],
       ['Yellow Pacamara Carbonic Maceration Nanolot'],
       ['Ethiopia Gera Genji Challa'],
       ['Yirgacheffe Mengesha Natural'],
       ['Tropical Summer Colombia La Sierra']], dtype=object)

In [ ]:
# Encode variables using get_dummies
X = pd.get_dummies(X)
X.head(10)

acidity_structure  aroma  flavor  roast_level  usd_per_oz  \
0                9.0    9.0     9.0            4        2.50   
1                8.0    9.0     9.0            4       13.33   
2                9.0    9.0     9.0            4        2.33   
3                9.0    9.0     9.0            4        1.71   
4                9.0    9.0     9.0            4        2.37   
5                7.0    9.0     9.0            4     1749.30   
6                8.0    9.0     9.0            4        1.33   
7                9.0    9.0     9.0            1     3811.12   
8                8.0    9.0     9.0            1     2667.78   
9                8.0    9.0     9.0            1        2.10   

   city_Albuquerque  city_Altadena  city_Antigua  city_Asheville  \
0                 0              0             0               0   
1                 0              0             0               0   
2                 0              0             0               0   
3                 0              0             0               0   
4                 0              0             0               0   
5                 0              0             0               0   
6                 0              0             1               0   
7                 0              0             0               0   
8                 0              0             0               0   
9                 0              0             0               0   

   city_Ashland  ...  state_ Uganda  state_ United Arab Emirates  state_ Utah  \
0             0  ...              0                            0            0   
1             0  ...              0                            0            0   
2             0  ...              0                            0            0   
3             0  ...              0                            0            0   
4             0  ...              0                            0            0   
5             0  ...              0                            0            0   
6             0  ...              0                            0            0   
7             0  ...              0                            0            0   
8             0  ...              0                            0            0   
9             0  ...              0                            0            0   

   state_ Vermont  state_ Virginia  state_ Virginia and Floyd, Virginia  \
0               0                1                                    0   
1               0                0                                    0   
2               0                0                                    0   
3               0                0                                    0   
4               0                1                                    0   
5               0                0                                    0   
6               0                0                                    0   
7               0                0                                    0   
8               0                0                                    0   
9               0                0                                    0   

   state_ Washingto  state_ Washington  state_ Wisconsin  state_ Wyoming  
0                 0                  0                 0               0  
1                 0                  0                 0               0  
2                 0                  0                 0               0  
3                 0                  0                 0               0  
4                 0                  0                 0               0  
5                 0                  0                 0               0  
6                 0                  0                 0               0  
7                 0                  0                 0               0  
8                 0                  0                 0               0  
9                 0                  0                 0               0  

[10 r

In [ ]:
# Splitting into Train and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [ ]:
# Create the StandardScaler instance
scaler = StandardScaler()

In [ ]:
# Fit the Standard Scaler with the training data
X_scaler = scaler.fit(X_train)

In [ ]:
# Scale the training data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Create the decision tree classifier instance
model = tree.DecisionTreeClassifier()

In [ ]:
# Fit the model
model = model.fit(X_train_scaled, y_train)

In [ ]:
# Making predictions using the testing data
predictions = model.predict(X_test_scaled)

In [ ]:
accuracy_score(y_test, predictions)


0.0038022813688212928

In [ ]:

pip install graphviz pydotplus

Note: you may need to restart the kernel to use updated packages.


In [ ]:
dot_data = tree.export_graphviz(model, out_file=None, 
                         feature_names=X.columns,  
                         filled=True, rounded=True,  
                         special_characters=True)  
graph = pydotplus.graph_from_dot_data(dot_data)  
Image(graph.create_png())

InvocationException: GraphViz's executables not found

In [ ]:
# Create DOT data
dot_data = tree.export_graphviz(
    model, out_file=None, feature_names=X.columns, filled=True
)

# Draw graph
graph = pydotplus.graph_from_dot_data(dot_data)

# Show graph
Image(graph.create_png())

InvocationException: GraphViz's executables not found